_target_: nuplan_extent.planning.training.modeling.models.gump_v1_1.GUMPV1_1
_convert_: 'all'

image_encoder:
  _target_: nuplan_extent.planning.training.modeling.models.encoders.raster_encoder_v2.RasterEncoderV3
  _convert_: 'all'
  backbone_name: 'resnet34'
  input_raster_names:
    - 'roadmap'
    - 'baseline_paths'
    - 'route'
    - 'ego_speed'
    - 'drivable_area'
    - 'static_agents_raster'
  pretrained: false
  output_stride: 32
  out_indices: [4]
  max_batch_size: -1
  lean: false
  out_dim: 512
  n_embed: 128

tokenizer:
  _target_: nuplan_extent.planning.training.modeling.models.tokenizers.kinetics_cached_tokenizer.KineticsCachedTokenizer
  _convert_: 'all'
  random_start: true

embedder:
  _target_: nuplan_extent.planning.training.modeling.models.embedders.kinetics_embedder.KineticsEmbedder
  _convert_: 'all'
  map_range: ${common_cfg.input_cfg.raster_map_bev_range}
  n_embd: 128
  hidden: 128

transition_model:
  _target_: nuplan_extent.planning.training.modeling.models.transition_models.kinetics_transition_model.KineticsTransitionModel
  _convert_: 'all'
  block_size: 256 # 145*3 7 second history max
  temperature: 1.0
  top_k: 10
  n_spatial_layer: 3
  n_temporal_layer: 3
  n_head: 4
  n_embd: 128

token_decoder:
  _target_: nuplan_extent.planning.training.modeling.models.decoders.kinetics_token_decoder.KineticsTokenDecoder
  _convert_: 'all'
  n_embed: 128
  num_rnn_layers: 1
  num_agent_attributes: 1
  block_size: 416
  temperature: 1.0
  topk: 20

render:
  _target_: nuplan_extent.planning.training.modeling.models.renders.kinetics_render.KineticsRender
  _convert_: 'all'

# postprocessor:
#   _target_: nuplan_extent.planning.training.modeling.models.post_processors.gump_naive_planner.GUMPNaivePlanner
#   _convert_: 'all'

# Parameters for predicted trajectory
future_trajectory_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: 'all'
  num_poses: ${common_cfg.output_cfg.trajectory_steps}  # number of poses in a trajectory
  time_horizon: ${common_cfg.output_cfg.time_horizon}  # [s] time horizon of all poses

# All feature builders
feature_builders:
  - _target_: nuplan_extent.planning.training.preprocessing.feature_builders.waymo_raster_feature_builder_v2.WaymoRasterFeatureBuilderV2
    _convert_: 'all'

    map_features:  # name of map features to be drawn and its color [0.0, 1.0] for encoding
      BASELINE_PATHS: 1.0
      EXTENDED_PUDO: 1.0
      SPEED_BUMP: 0.5
      CROSSWALK: 0.5
      
    raster_names:
      - 'roadmap'
      - 'baseline_paths'
      - 'ego_speed'
      - 'drivable_area'
      - 'static_agents_raster'
      - 'route'
   
    target_width: 416
    target_height: 416
    target_pixel_size: 0.5
    ego_width: 2.297
    ego_front_length: 4.049
    ego_rear_length: 1.127
    ego_longitudinal_offset: 0.0
    baseline_path_thickness: 1
    past_time_horizon: 2.0
    past_num_poses: 4
    max_speed_normalizer: 24.0 
    use_uint8: true
    feature_time_interval: 0.5  # [s] time interval of each pose

  - _target_: nuplan_extent.planning.training.preprocessing.feature_builders.waymo_vector_feature_builder_v2.WaymoVectorFeatureBuilderV2
    agent_features:
      - 'VEHICLE'
      - 'PEDESTRIAN'
      - 'BICYCLE'
    radius: 150
    longitudinal_offset: 0.0
    past_time_horizon: 1.0
    past_num_steps: 2
    future_time_horizon: 8.0
    future_num_steps: 16
    num_max_agents:
      - 256
      - 128
      - 32
  - _target_: nuplan_extent.planning.training.preprocessing.feature_builders.horizon_tokenized_builder.HorizonTokenizedDataBuilder
    _convert_: 'all'

target_builders:
  - _target_: nuplan_extent.planning.training.preprocessing.target_builders.sim_agents_target_builder.SimAgentsTargetBuilder
    _convert_: 'all'
    future_trajectory_sampling: ${model.future_trajectory_sampling}    

num_paralell_scenario: 32

# downstream_task: ${common_cfg.downstream_task}
downstream_task: 'scenario_extrapolation' # 'planning'
num_imagine_frames: 16
num_conditioned_frames: 3